name: Bump Provider and Module Versions

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: The environment of the Registry
        options:
          - Development
          - Production

jobs:
  bump-versions:
    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}
    permissions:
      contents: write
      actions: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './src/go.mod'

      - name: Run version bump script
        working-directory: ./src
        run: go run ./cmd/bump-versions

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'modules/**/* providers/**/*'
          commit_user_name: Auto Version Bumper